# See here for image contents: https://github.com/microsoft/vscode-dev-containers/blob/v0.185.0/containers/python-3/.devcontainer/base.Dockerfile
# See here for image contents: https://github.com/microsoft/vscode-dev-containers/blob/v0.185.0/containers/python-3/.devcontainer/base.Dockerfile
# FROM mambaorg/micromamba:0.24.0
FROM mambaorg/micromamba:0-buster-slim
COPY --chown=$MAMBA_USER:$MAMBA_USER mamba_env.yaml /tmp/mamba_env.yaml
RUN micromamba install -y -n base -f /tmp/mamba_env.yaml && \
    micromamba clean --all --yes

ARG MAMBA_DOCKERFILE_ACTIVATE=1  # (otherwise python will not be found)
RUN python -c 'print("Hello world")'

# [Optional] If your pip requirements rarely change, uncomment this section to add them to the image.
# COPY requirements.txt /tmp/pip-tmp/
# RUN pip3 --disable-pip-version-check --no-cache-dir install -r /tmp/pip-tmp/requirements.txt \
#    && rm -rf /tmp/pip-tmp

# [Optional] Uncomment this section to install additional OS packages.
# RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
#     && apt-get -y install --no-install-recommends <your-package-list-here>

# [Optional] Uncomment this line to install global node packages.
# RUN su vscode -c "source /usr/local/share/nvm/nvm.sh && npm install -g <your-package-here>" 2>&1